/**
 * ============================================================
 * CELEBRATIONS RESTAURANT — CENTRALIZED DATA
 * ============================================================
 * 
 * This file contains ALL editable restaurant data.
 * To update any information (prices, menu items, images, etc.),
 * edit the relevant section below.
 * 
 * PRICE NOTES:
 * - Prices sourced from Swiggy, Magicpin, JustDial (Sept 2026)
 * - Items marked "price: null" need client confirmation
 * - Prices may vary from dine-in; confirm with restaurant
 * 
 * IMAGE NOTES:
 * - Images use Unsplash URLs as temporary placeholders
 * - Replace with actual restaurant photographs when available
 * ============================================================
 */

const RESTAURANT = {
  name: "Celebrations Restaurant",
  nameTelugu: "సెలెబ్రేషన్స్ రెస్టారెంట్",
  tagline: "Where Every Meal Becomes a Celebration",
  description: "Delicious biryanis, Indian favourites, Chinese specialities, grills and more — served with warmth in the heart of Pendurthi.",
  phone: "09030994922",
  phoneDisplay: "090309 94922",
  address: "Police Station, 1-93, Sarada Nagar, Karmika Nagar, Pendurthi, Chinnamusidivada, Andhra Pradesh 531173, India",
  addressShort: "Pendurthi, Visakhapatnam",
  hours: "10:30 AM – 11:00 PM",
  hoursNote: "Open Daily",
  priceRange: "₹200 – ₹1,200 per person",
  costForTwo: "~₹1,000 for two",
  rating: 4.3,
  ratingMax: 5,
  reviewCount: "4,978",
  reviewCountNum: 4978,
  cuisines: ["Biryani", "Indian", "North Indian", "South Indian", "Chinese", "Grill", "Tandoori"],
  services: ["Dine-in", "Takeaway", "No-contact Delivery", "Online Ordering"],

  // Map coordinates for Pendurthi, Visakhapatnam
  coordinates: {
    lat: 17.7547,
    lng: 83.2350
  },

  // Links
  googleMapsUrl: "https://www.google.com/maps/search/Celebrations+Restaurant+Pendurthi+Visakhapatnam",
  googleReviewsUrl: "https://www.google.com/maps/search/Celebrations+Restaurant+Pendurthi+Visakhapatnam",
  orderOnlineUrl: "https://www.swiggy.com/restaurants/celebrations-pendurthi",
  
  // Social media — only add verified accounts
  social: {
    // instagram: null,
    // facebook: null,
    // youtube: null,
  }
};

// ============================================================
// MENU DATA
// ============================================================
// type: "veg" | "nonveg"
// category: Main grouping
// subCategory: Sub-grouping within category  
// price: Number in INR. null = needs client confirmation
// popular: true if a customer favourite
// featured: true if shown in featured section
// spiceLevel: 0-3 (0=mild, 1=medium, 2=spicy, 3=very spicy)
// image: URL to food image (replace with actual photos)
// ============================================================

const MENU_ITEMS = [

  // ============================================================
  // VEG SOUPS
  // ============================================================
  {
    id: "vs-1",
    name: "Veg Sweet Corn Soup",
    category: "Soups",
    type: "veg",
    price: 120,
    description: "Creamy sweet corn soup with fresh vegetables",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vs-2",
    name: "Veg Manchow Soup",
    category: "Soups",
    type: "veg",
    price: 120,
    description: "Indo-Chinese soup with crispy noodles on top",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vs-3",
    name: "Veg Hot & Sour Soup",
    category: "Soups",
    type: "veg",
    price: 120,
    description: "Tangy and spicy soup with mixed vegetables",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1603105037880-880cd4edfb0d?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vs-4",
    name: "Tomato Soup",
    category: "Soups",
    type: "veg",
    price: 100,
    description: "Classic creamy tomato soup",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1547592180-85f173990554?w=400&q=80",
    popular: false,
    featured: false,
  },

  // ============================================================
  // NON-VEG SOUPS
  // ============================================================
  {
    id: "ns-1",
    name: "Chicken Manchow Soup",
    category: "Soups",
    type: "nonveg",
    price: 140,
    description: "Indo-Chinese chicken soup with crispy noodles",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1583577612013-4e2b1b0b0b1a?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "ns-2",
    name: "Chicken Sweet Corn Soup",
    category: "Soups",
    type: "nonveg",
    price: 140,
    description: "Creamy sweet corn soup with tender chicken",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "ns-3",
    name: "Chicken Hot & Sour Soup",
    category: "Soups",
    type: "nonveg",
    price: 140,
    description: "Spicy and tangy chicken soup",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "ns-4",
    name: "Chicken Soup",
    category: "Soups",
    type: "nonveg",
    price: 130,
    description: "Classic chicken broth with herbs and spices",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=400&q=80",
    popular: true,
    featured: false,
  },

  // ============================================================
  // VEG STARTERS (CHINESE)
  // ============================================================
  {
    id: "vst-1",
    name: "Veg Manchurian",
    category: "Starters",
    type: "veg",
    price: 200,
    description: "Deep-fried vegetable balls in tangy Manchurian sauce",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vst-2",
    name: "Mushroom Manchurian",
    category: "Starters",
    type: "veg",
    price: 240,
    description: "Crispy mushroom fritters tossed in spicy Manchurian gravy",
    spiceLevel: 1,
    image: "images/chilli-mushroom.jpg",
    popular: true,
    featured: true,
  },
  {
    id: "vst-3",
    name: "Paneer Manchurian",
    category: "Starters",
    type: "veg",
    price: 250,
    description: "Golden paneer cubes in Manchurian sauce",
    spiceLevel: 1,
    image: "images/paneer-65.jpg",
    popular: false,
    featured: false,
  },
  {
    id: "vst-4",
    name: "Chilli Paneer",
    category: "Starters",
    type: "veg",
    price: 260,
    description: "Spicy paneer stir-fried with peppers and onions",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "vst-5",
    name: "Chilli Mushroom",
    category: "Starters",
    type: "veg",
    price: 240,
    description: "Crispy mushrooms in a fiery chilli sauce",
    spiceLevel: 2,
    image: "images/chilli-mushroom.jpg",
    popular: false,
    featured: false,
  },
  {
    id: "vst-6",
    name: "Crispy Baby Corn",
    category: "Starters",
    type: "veg",
    price: 200,
    description: "Crunchy baby corn with a spiced coating",
    spiceLevel: 1,
    image: "images/crispy-baby-corn.jpg",
    popular: false,
    featured: false,
  },
  {
    id: "vst-7",
    name: "Gobi Manchurian",
    category: "Starters",
    type: "veg",
    price: 200,
    description: "Batter-fried cauliflower in tangy Manchurian sauce",
    spiceLevel: 1,
    image: "images/gobi-manchurian.jpg",
    popular: false,
    featured: false,
  },
  {
    id: "vst-8",
    name: "Paneer 65",
    category: "Starters",
    type: "veg",
    price: 260,
    description: "Deep-fried paneer with South Indian spices",
    spiceLevel: 2,
    image: "images/paneer-65.jpg",
    popular: false,
    featured: false,
  },

  // ============================================================
  // NON-VEG STARTERS
  // ============================================================
  {
    id: "nvst-1",
    name: "Chicken 65",
    category: "Starters",
    type: "nonveg",
    price: 290,
    description: "Classic spicy deep-fried chicken with curry leaves",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1610057099443-fde6c99db9e1?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "nvst-2",
    name: "Chicken Lollipop",
    category: "Starters",
    type: "nonveg",
    price: 340,
    description: "Crispy chicken drumettes shaped like lollipops (6 pcs)",
    spiceLevel: 1,
    image: "images/chicken-lollipop.jpg",
    popular: true,
    featured: true,
    servingInfo: "6 Pcs",
  },
  {
    id: "nvst-3",
    name: "Apollo Fish",
    category: "Starters",
    type: "nonveg",
    price: 340,
    description: "Iconic Hyderabadi spicy fish fry with bold flavours",
    spiceLevel: 3,
    image: "images/apollo-fish.jpg",
    popular: true,
    featured: true,
  },
  {
    id: "nvst-4",
    name: "Chicken Manchurian",
    category: "Starters",
    type: "nonveg",
    price: 280,
    description: "Indo-Chinese chicken in a tangy Manchurian sauce",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1527477396000-e27163b4bbb0?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvst-5",
    name: "Chilli Chicken",
    category: "Starters",
    type: "nonveg",
    price: 290,
    description: "Spicy chicken tossed with green chillies and bell peppers",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880049?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "nvst-6",
    name: "Dragon Chicken",
    category: "Starters",
    type: "nonveg",
    price: 300,
    description: "Crispy chicken in a sweet and spicy dragon sauce",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvst-7",
    name: "Prawn Fry",
    category: "Starters",
    type: "nonveg",
    price: 340,
    description: "Crispy fried prawns with spices",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1565680018093-ebb6b9ab5460?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvst-8",
    name: "Fish Fry",
    category: "Starters",
    type: "nonveg",
    price: 320,
    description: "Andhra-style masala fish fry",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?w=400&q=80",
    popular: false,
    featured: false,
  },

  // ============================================================
  // VEG BIRYANI
  // ============================================================
  {
    id: "vb-1",
    name: "Veg Biryani",
    category: "Biryani",
    type: "veg",
    price: 220,
    description: "Fragrant basmati rice with mixed vegetables and aromatic spices",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vb-2",
    name: "Avakai Biryani",
    category: "Biryani",
    type: "veg",
    price: 220,
    description: "Biryani infused with tangy Andhra mango pickle flavour",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vb-3",
    name: "Gongura Veg Biryani",
    category: "Biryani",
    type: "veg",
    price: 230,
    description: "Biryani with tangy gongura (sorrel leaves) masala",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b7?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vb-4",
    name: "Ulavacharu Biryani",
    category: "Biryani",
    type: "veg",
    price: 230,
    description: "Biryani prepared with traditional ulavacharu (horse gram broth)",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vb-5",
    name: "Mixed Veg Biryani",
    category: "Biryani",
    type: "veg",
    price: 250,
    description: "Loaded biryani with a medley of fresh seasonal vegetables",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vb-6",
    name: "Paneer Biryani",
    category: "Biryani",
    type: "veg",
    price: 250,
    description: "Rich biryani loaded with soft paneer cubes",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "vb-7",
    name: "Paneer Tikka Biryani",
    category: "Biryani",
    type: "veg",
    price: 270,
    description: "Biryani with smoky tandoori paneer tikka pieces",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vb-8",
    name: "Mushroom Biryani",
    category: "Biryani",
    type: "veg",
    price: 250,
    description: "Aromatic biryani with tender mushroom pieces",
    spiceLevel: 1,
    image: "images/chilli-mushroom.jpg",
    popular: false,
    featured: false,
  },
  {
    id: "vb-9",
    name: "Kaju Biryani",
    category: "Biryani",
    type: "veg",
    price: 280,
    description: "Premium biryani enriched with cashew nuts",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=400&q=80",
    popular: false,
    featured: false,
  },

  // ============================================================
  // NON-VEG BIRYANI
  // ============================================================
  {
    id: "nvb-1",
    name: "Chicken Dum Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 280,
    description: "Slow-cooked Hyderabadi-style dum biryani with tender chicken",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&q=80",
    popular: true,
    featured: true,
  },
  {
    id: "nvb-2",
    name: "Chicken Fry Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 300,
    description: "Flavourful biryani topped with crispy fried chicken",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "nvb-3",
    name: "Gongura Chicken Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 300,
    description: "Signature Andhra biryani with tangy gongura and chicken",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b7?w=400&q=80",
    popular: true,
    featured: true,
  },
  {
    id: "nvb-4",
    name: "Chicken Boneless Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 300,
    description: "Boneless chicken pieces in aromatic biryani rice",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-5",
    name: "Chicken Mughlai Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 310,
    description: "Rich Mughlai-style biryani with royal spices and chicken",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-6",
    name: "Chicken Avakaya Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 320,
    description: "Biryani with bold avakaya (mango pickle) flavour and chicken",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-7",
    name: "Chicken Tikka Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 320,
    description: "Biryani loaded with smoky tandoori chicken tikka",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-8",
    name: "Chicken Ulavacharu Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 300,
    description: "Chicken biryani infused with traditional ulavacharu flavour",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-9",
    name: "Special Chicken Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 320,
    description: "Chef's special chicken biryani with extra flavour",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1642821373181-d31a6a2d39b0?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "nvb-10",
    name: "Special Chettinad Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 320,
    description: "Fiery Chettinad-style biryani with aromatic spices",
    spiceLevel: 3,
    image: "https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-11",
    name: "Kadai Chicken Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 310,
    description: "Biryani with kadai-style spiced chicken",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b7?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-12",
    name: "Kalmi Chicken Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 320,
    description: "Biryani with succulent kalmi chicken drumstick",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-13",
    name: "Lollipop Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 340,
    description: "Unique biryani served with chicken lollipop",
    spiceLevel: 1,
    image: "images/chicken-lollipop.jpg",
    popular: true,
    featured: false,
  },
  {
    id: "nvb-14",
    name: "Tandoori Joint Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 350,
    description: "Biryani paired with a smoky tandoori chicken joint",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-15",
    name: "Tandoori Double Joint Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 420,
    description: "Premium biryani with two tandoori chicken joints",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1642821373181-d31a6a2d39b0?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-16",
    name: "Egg Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 200,
    description: "Flavourful biryani with whole boiled eggs",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-17",
    name: "Fish Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 320,
    description: "Aromatic biryani with fresh fish pieces",
    spiceLevel: 1,
    image: "images/apollo-fish.jpg",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-18",
    name: "Prawn Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 340,
    description: "Premium biryani with juicy prawns",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1565680018093-ebb6b9ab5460?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-19",
    name: "Prawn Avakai Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 360,
    description: "Prawn biryani with tangy avakaya flavour",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1559742811-822873691df8?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-20",
    name: "Prawn Mughlai Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 370,
    description: "Rich Mughlai-style biryani with prawns",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1565680018093-ebb6b9ab5460?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-21",
    name: "Gongura Mutton Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 360,
    description: "Tender mutton biryani with tangy gongura leaves",
    spiceLevel: 2,
    image: "images/mutton-biryani.jpg",
    popular: true,
    featured: false,
  },
  {
    id: "nvb-22",
    name: "Gongura Prawn Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 370,
    description: "Prawn biryani infused with gongura masala",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1559742811-822873691df8?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-23",
    name: "Mutton Mughlai Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 340,
    description: "Royal Mughlai biryani with succulent mutton",
    spiceLevel: 1,
    image: "images/mutton-biryani.jpg",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-24",
    name: "Mutton Ulavacharu Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 340,
    description: "Mutton biryani with earthy ulavacharu flavour",
    spiceLevel: 1,
    image: "images/mutton-biryani.jpg",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-25",
    name: "Mutton Fry Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 350,
    description: "Biryani topped with spicy fried mutton pieces",
    spiceLevel: 2,
    image: "images/mutton-biryani.jpg",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-26",
    name: "Mutton Keema Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 400,
    description: "Biryani with richly spiced minced mutton keema",
    spiceLevel: 1,
    image: "images/mutton-biryani.jpg",
    popular: false,
    featured: false,
  },
  {
    id: "nvb-27",
    name: "Mixed Mughlai Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 350,
    description: "Lavish biryani with a mix of chicken and mutton",
    spiceLevel: 1,
    image: "images/mutton-biryani.jpg",
    popular: true,
    featured: true,
  },
  {
    id: "nvb-28",
    name: "Rajulu Biryani",
    category: "Biryani",
    type: "nonveg",
    price: 380,
    description: "Signature royal biryani preparation",
    spiceLevel: 1,
    image: "images/mutton-biryani.jpg",
    popular: false,
    featured: false,
  },

  // ============================================================
  // VEG CURRIES
  // ============================================================
  {
    id: "vc-1",
    name: "Kadai Paneer",
    category: "Curries",
    type: "veg",
    price: 270,
    description: "Paneer cooked in a spicy kadai masala with bell peppers",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80",
    popular: true,
    featured: true,
  },
  {
    id: "vc-2",
    name: "Shahi Paneer",
    category: "Curries",
    type: "veg",
    price: 300,
    description: "Creamy paneer in a rich cashew and tomato gravy",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "vc-3",
    name: "Paneer Butter Masala",
    category: "Curries",
    type: "veg",
    price: 290,
    description: "Paneer cubes in velvety butter tomato gravy",
    spiceLevel: 0,
    image: "images/paneer-butter-masala.jpg",
    popular: true,
    featured: false,
  },
  {
    id: "vc-4",
    name: "Paneer Chettinad",
    category: "Curries",
    type: "veg",
    price: 270,
    description: "Paneer in a fiery Chettinad spice blend",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vc-5",
    name: "Kaju Masala",
    category: "Curries",
    type: "veg",
    price: 310,
    description: "Cashew nuts in a rich and creamy masala gravy",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vc-6",
    name: "Methi Chaman",
    category: "Curries",
    type: "veg",
    price: 290,
    description: "Paneer with fresh fenugreek leaves in a creamy gravy",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vc-7",
    name: "Tomato Kaju Curry",
    category: "Curries",
    type: "veg",
    price: 270,
    description: "Cashews simmered in a tangy tomato gravy",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vc-8",
    name: "Dal Tadka",
    category: "Curries",
    type: "veg",
    price: 180,
    description: "Yellow lentils tempered with aromatic spices and ghee",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&q=80",
    popular: false,
    featured: false,
  },

  // ============================================================
  // NON-VEG CURRIES
  // ============================================================
  {
    id: "nvc-1",
    name: "Butter Chicken",
    category: "Curries",
    type: "nonveg",
    price: 300,
    description: "Classic creamy butter chicken in makhani gravy",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400&q=80",
    popular: true,
    featured: true,
  },
  {
    id: "nvc-2",
    name: "Chicken Curry",
    category: "Curries",
    type: "nonveg",
    price: 280,
    description: "Homestyle chicken curry with warming spices",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "nvc-3",
    name: "Chicken Chettinad",
    category: "Curries",
    type: "nonveg",
    price: 300,
    description: "Spicy Chettinad-style chicken curry from South India",
    spiceLevel: 3,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvc-4",
    name: "Mutton Gongura",
    category: "Curries",
    type: "nonveg",
    price: 340,
    description: "Andhra-style mutton cooked with tangy gongura leaves",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "nvc-5",
    name: "Mutton Rogan Josh",
    category: "Curries",
    type: "nonveg",
    price: 370,
    description: "Kashmiri-style mutton in a rich red gravy",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1545247181-516773cae754?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvc-6",
    name: "Mutton Fry",
    category: "Curries",
    type: "nonveg",
    price: 360,
    description: "Dry-fried mutton with Andhra spices",
    spiceLevel: 2,
    image: "images/mutton-biryani.jpg",
    popular: false,
    featured: false,
  },
  {
    id: "nvc-7",
    name: "Mutton Rajadhani",
    category: "Curries",
    type: "nonveg",
    price: 340,
    description: "Tender mutton in a royal-style gravy",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvc-8",
    name: "Mutton Curry",
    category: "Curries",
    type: "nonveg",
    price: 450,
    description: "Slow-cooked mutton in aromatic curry",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvc-9",
    name: "Fish Curry (Boneless)",
    category: "Curries",
    type: "nonveg",
    price: 360,
    description: "Andhra-style boneless fish curry",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvc-10",
    name: "Prawn Chettinad",
    category: "Curries",
    type: "nonveg",
    price: 380,
    description: "Prawns in a bold Chettinad pepper masala",
    spiceLevel: 3,
    image: "https://images.unsplash.com/photo-1565680018093-ebb6b9ab5460?w=400&q=80",
    popular: false,
    featured: false,
  },

  // ============================================================
  // VEG TANDOORI
  // ============================================================
  {
    id: "vt-1",
    name: "Paneer Tikka",
    category: "Tandoori",
    type: "veg",
    price: 260,
    description: "Marinated paneer cubes grilled in the tandoor",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "vt-2",
    name: "Mushroom Tikka",
    category: "Tandoori",
    type: "veg",
    price: 240,
    description: "Tandoor-grilled mushrooms with spiced marinade",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80",
    popular: false,
    featured: false,
  },

  // ============================================================
  // NON-VEG TANDOORI
  // ============================================================
  {
    id: "nvt-1",
    name: "Tandoori Chicken (Full)",
    category: "Tandoori",
    type: "nonveg",
    price: 450,
    description: "Whole chicken marinated in yoghurt and spices, charred in the tandoor",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1610057099443-fde6c99db9e1?w=400&q=80",
    popular: true,
    featured: true,
  },
  {
    id: "nvt-2",
    name: "Tandoori Chicken (Half)",
    category: "Tandoori",
    type: "nonveg",
    price: 260,
    description: "Half tandoori chicken with smoky charred flavour",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1606491956689-2ea866880049?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "nvt-3",
    name: "Chicken Tikka",
    category: "Tandoori",
    type: "nonveg",
    price: 290,
    description: "Boneless chicken pieces grilled to perfection in the tandoor",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&q=80",
    popular: false,
    featured: false,
  },

  // ============================================================
  // VEG NOODLES
  // ============================================================
  {
    id: "vn-1",
    name: "Veg Hakka Noodles",
    category: "Noodles",
    type: "veg",
    price: 190,
    description: "Stir-fried noodles with crisp vegetables",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vn-2",
    name: "Veg Schezwan Noodles",
    category: "Noodles",
    type: "veg",
    price: 200,
    description: "Spicy Schezwan-style stir-fried noodles",
    spiceLevel: 2,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400&q=80",
    popular: false,
    featured: false,
  },

  // ============================================================
  // NON-VEG NOODLES
  // ============================================================
  {
    id: "nvn-1",
    name: "Chicken Noodles",
    category: "Noodles",
    type: "nonveg",
    price: 230,
    description: "Stir-fried noodles with tender chicken strips",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvn-2",
    name: "Mixed Non-Veg Noodles",
    category: "Noodles",
    type: "nonveg",
    price: 270,
    description: "Loaded noodles with chicken, egg and prawns",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "nvn-3",
    name: "Egg Noodles",
    category: "Noodles",
    type: "nonveg",
    price: 200,
    description: "Classic egg noodles tossed with vegetables",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&q=80",
    popular: false,
    featured: false,
  },

  // ============================================================
  // VEG RICE
  // ============================================================
  {
    id: "vr-1",
    name: "Veg Fried Rice",
    category: "Rice",
    type: "veg",
    price: 190,
    description: "Classic fried rice with mixed vegetables",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "vr-2",
    name: "Paneer Fried Rice",
    category: "Rice",
    type: "veg",
    price: 230,
    description: "Fried rice with paneer cubes and vegetables",
    spiceLevel: 1,
    image: "images/paneer-65.jpg",
    popular: false,
    featured: false,
  },
  {
    id: "vr-3",
    name: "Mushroom Fried Rice",
    category: "Rice",
    type: "veg",
    price: 230,
    description: "Fried rice tossed with sautéed mushrooms",
    spiceLevel: 1,
    image: "images/chilli-mushroom.jpg",
    popular: false,
    featured: false,
  },
  {
    id: "vr-4",
    name: "Mixed Veg Fried Rice",
    category: "Rice",
    type: "veg",
    price: 250,
    description: "Fried rice loaded with seasonal vegetables",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vr-5",
    name: "Kaju Fried Rice",
    category: "Rice",
    type: "veg",
    price: 280,
    description: "Premium fried rice with roasted cashews",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "vr-6",
    name: "Ginger Corn Fried Rice",
    category: "Rice",
    type: "veg",
    price: 220,
    description: "Fried rice with ginger and sweet corn",
    spiceLevel: 1,
    image: "images/crispy-baby-corn.jpg",
    popular: false,
    featured: false,
  },

  // ============================================================
  // NON-VEG RICE
  // ============================================================
  {
    id: "nvr-1",
    name: "Chicken Fried Rice",
    category: "Rice",
    type: "nonveg",
    price: 240,
    description: "Fried rice with seasoned chicken pieces",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "nvr-2",
    name: "Egg Fried Rice",
    category: "Rice",
    type: "nonveg",
    price: 190,
    description: "Classic egg fried rice with vegetables",
    spiceLevel: 1,
    image: "https://images.unsplash.com/photo-1552611052-33e04de081de?w=400&q=80",
    popular: false,
    featured: false,
  },

  // ============================================================
  // INDIAN BREADS (shared — veg)
  // ============================================================
  {
    id: "br-1",
    name: "Roti",
    category: "Breads",
    type: "veg",
    price: 30,
    description: "Soft whole wheat Indian flatbread",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "br-2",
    name: "Butter Roti",
    category: "Breads",
    type: "veg",
    price: 35,
    description: "Roti brushed with fresh butter",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "br-3",
    name: "Plain Naan",
    category: "Breads",
    type: "veg",
    price: 45,
    description: "Soft tandoor-baked naan bread",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "br-4",
    name: "Butter Naan",
    category: "Breads",
    type: "veg",
    price: 55,
    description: "Naan baked in tandoor with a layer of butter",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "br-5",
    name: "Garlic Naan",
    category: "Breads",
    type: "veg",
    price: 65,
    description: "Naan topped with fresh garlic and butter",
    spiceLevel: 0,
    image: "images/garlic-naan.jpg",
    popular: false,
    featured: false,
  },
  {
    id: "br-6",
    name: "Tandoori Roti",
    category: "Breads",
    type: "veg",
    price: 40,
    description: "Whole wheat roti baked in the tandoor",
    spiceLevel: 0,
    image: "images/garlic-naan.jpg",
    popular: false,
    featured: false,
  },

  // ============================================================
  // DRINKS — MOCKTAILS & MILKSHAKES
  // ============================================================
  {
    id: "dr-1",
    name: "Vanilla Milkshake",
    category: "Drinks",
    type: "veg",
    price: 100,
    description: "Creamy vanilla flavoured milkshake",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "dr-2",
    name: "Chocolate Milkshake",
    category: "Drinks",
    type: "veg",
    price: 110,
    description: "Rich and indulgent chocolate milkshake",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&q=80",
    popular: true,
    featured: false,
  },
  {
    id: "dr-3",
    name: "Butterscotch Milkshake",
    category: "Drinks",
    type: "veg",
    price: 110,
    description: "Smooth butterscotch flavoured milkshake",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1553787499-6f9133860278?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "dr-4",
    name: "Strawberry Milkshake",
    category: "Drinks",
    type: "veg",
    price: 110,
    description: "Refreshing strawberry flavoured milkshake",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1553787499-6f9133860278?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "dr-5",
    name: "Lassi (Sweet)",
    category: "Drinks",
    type: "veg",
    price: 80,
    description: "Traditional Indian yoghurt drink",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1623065422902-30f2a5ed1956?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "dr-6",
    name: "Fresh Lime Soda",
    category: "Drinks",
    type: "veg",
    price: 60,
    description: "Refreshing lime soda — sweet or salt",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "dr-7",
    name: "Soft Drink",
    category: "Drinks",
    type: "veg",
    price: 40,
    description: "Chilled aerated beverage",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "dr-8",
    name: "Water Bottle",
    category: "Drinks",
    type: "veg",
    price: 20,
    description: "Packaged drinking water (1L)",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400&q=80",
    popular: false,
    featured: false,
  },

  // ============================================================
  // DESSERTS
  // ============================================================
  {
    id: "ds-1",
    name: "Gulab Jamun",
    category: "Desserts",
    type: "veg",
    price: 80,
    description: "Soft milk dumplings soaked in rose-flavoured syrup",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1666190094665-2515c7e01e72?w=400&q=80",
    popular: true,
    featured: false,
    servingInfo: "2 Pcs",
  },
  {
    id: "ds-2",
    name: "Double Ka Meetha",
    category: "Desserts",
    type: "veg",
    price: 100,
    description: "Hyderabadi bread pudding with saffron and nuts",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1587314168485-3236d6710814?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "ds-3",
    name: "Ice Cream",
    category: "Desserts",
    type: "veg",
    price: 80,
    description: "Chilled ice cream — choice of flavours",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400&q=80",
    popular: false,
    featured: false,
  },
  {
    id: "ds-4",
    name: "Qubani Ka Meetha",
    category: "Desserts",
    type: "veg",
    price: 120,
    description: "Traditional apricot dessert served with ice cream",
    spiceLevel: 0,
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&q=80",
    popular: false,
    featured: false,
  },
];


// ============================================================
// FEATURED DISHES (references to MENU_ITEMS by id)
// ============================================================
const FEATURED_IDS = [
  "nvb-3",   // Gongura Chicken Biryani — star item
  "nvb-1",   // Chicken Dum Biryani
  "nvst-3",  // Apollo Fish
  "vc-1",    // Kadai Paneer
  "nvc-1",   // Butter Chicken
  "nvb-27",  // Mixed Mughlai Biryani
  "nvst-2",  // Chicken Lollipop
  "nvt-1",   // Tandoori Chicken (Full)
];


// ============================================================
// GALLERY IMAGES
// ============================================================
// Replace these Unsplash URLs with actual restaurant photos
// category: "food" | "biryani" | "veg" | "nonveg" | "restaurant" | "ambience" | "drinks"
// ============================================================
const GALLERY_IMAGES = [
  {
    src: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=600&q=80",
    alt: "Aromatic Hyderabadi-style chicken biryani served in a traditional handi",
    category: "biryani",
  },
  {
    src: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&q=80",
    alt: "Vegetable biryani with fragrant basmati rice and fresh herbs",
    category: "biryani",
  },
  {
    src: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&q=80",
    alt: "Rich paneer curry served in a traditional bowl",
    category: "veg",
  },
  {
    src: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&q=80",
    alt: "Butter chicken in creamy tomato gravy garnished with cream",
    category: "nonveg",
  },
  {
    src: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&q=80",
    alt: "Tandoori chicken with charred edges served on a sizzler plate",
    category: "nonveg",
  },
  {
    src: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&q=80",
    alt: "Fresh naan and roti bread served with accompaniments",
    category: "food",
  },
  {
    src: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=600&q=80",
    alt: "Paneer tikka with colourful bell peppers and onions",
    category: "veg",
  },
  {
    src: "https://images.unsplash.com/photo-1610057099443-fde6c99db9e1?w=600&q=80",
    alt: "Crispy fried chicken starters with garnish",
    category: "nonveg",
  },
  {
    src: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&q=80",
    alt: "Refreshing milkshakes and cold beverages",
    category: "drinks",
  },
  {
    src: "https://images.unsplash.com/photo-1666190094665-2515c7e01e72?w=600&q=80",
    alt: "Traditional Indian desserts",
    category: "drinks",
  },
  {
    src: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80",
    alt: "Warm restaurant interior with ambient lighting",
    category: "ambience",
  },
  {
    src: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80",
    alt: "Elegant restaurant dining area",
    category: "restaurant",
  },
  {
    src: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80",
    alt: "Restaurant ambience with cozy seating arrangement",
    category: "ambience",
  },
  {
    src: "https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?w=600&q=80",
    alt: "Fresh fish fry with Andhra spices",
    category: "nonveg",
  },
  {
    src: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=600&q=80",
    alt: "Vegetarian Chinese starters with manchurian sauce",
    category: "veg",
  },
  {
    src: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80",
    alt: "Stir-fried noodles with fresh vegetables",
    category: "food",
  },
];


// ============================================================
// MENU CATEGORIES for filter UI
// ============================================================
const MENU_CATEGORIES = [
  { key: "all", label: "All" },
  { key: "Soups", label: "Soups" },
  { key: "Starters", label: "Starters" },
  { key: "Biryani", label: "Biryani" },
  { key: "Curries", label: "Curries" },
  { key: "Tandoori", label: "Tandoori" },
  { key: "Rice", label: "Rice" },
  { key: "Noodles", label: "Noodles" },
  { key: "Breads", label: "Breads" },
  { key: "Drinks", label: "Drinks" },
  { key: "Desserts", label: "Desserts" },
];

// Gallery filter categories
const GALLERY_CATEGORIES = [
  { key: "all", label: "All" },
  { key: "food", label: "Food" },
  { key: "biryani", label: "Biryani" },
  { key: "veg", label: "Veg" },
  { key: "nonveg", label: "Non-Veg" },
  { key: "restaurant", label: "Restaurant" },
  { key: "ambience", label: "Ambience" },
  { key: "drinks", label: "Drinks & Desserts" },
];
